require("prototypes/building")
require("prototypes/car")
require("prototypes/character")
require("prototypes/explosion")
require("prototypes/fire")
require("prototypes/locomotive")
require("prototypes/lut")
require("prototypes/projectile")
require("prototypes/small-lamp")
-- require("prototypes/spidertron")